CREATE TABLE IF NOT EXISTS clients (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key TEXT UNIQUE NOT NULL,
    capacity BIGINT NOT NULL CHECK (capacity >= 0),
    refill_rate INTERVAL NOT NULL CHECK (refill_rate > INTERVAL '0 seconds'),
    unlimited BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_client_key ON clients(key);